require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tournaments", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Tournament. As you add validations to Tournament, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # TournamentsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tournament.create! valid_attributes
      get tournaments_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tournament = Tournament.create! valid_attributes
      get tournament_url(tournament), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tournament" do
        expect {
          post tournaments_url,
               params: { tournament: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Tournament, :count).by(1)
      end

      it "renders a JSON response with the new tournament" do
        post tournaments_url,
             params: { tournament: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tournament" do
        expect {
          post tournaments_url,
               params: { tournament: invalid_attributes }, as: :json
        }.to change(Tournament, :count).by(0)
      end

      it "renders a JSON response with errors for the new tournament" do
        post tournaments_url,
             params: { tournament: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tournament" do
        tournament = Tournament.create! valid_attributes
        patch tournament_url(tournament),
              params: { tournament: invalid_attributes }, headers: valid_headers, as: :json
        tournament.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the tournament" do
        tournament = Tournament.create! valid_attributes
        patch tournament_url(tournament),
              params: { tournament: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq("application/json")
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the tournament" do
        tournament = Tournament.create! valid_attributes
        patch tournament_url(tournament),
              params: { tournament: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tournament" do
      tournament = Tournament.create! valid_attributes
      expect {
        delete tournament_url(tournament), headers: valid_headers, as: :json
      }.to change(Tournament, :count).by(-1)
    end
  end
end
